#!/bin/bash
# Step 4: Download, build, and install DSpace 7.6
# Run as root on hrepolyREP (192.168.26.3)

set -euo pipefail

BLUE='\033[0;34m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
log()  { echo -e "${BLUE}[$(date +%H:%M:%S)]${NC} $1"; }
ok()   { echo -e "${GREEN}[OK]${NC} $1"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }

DSPACE_VERSION="7.6.3"
DSPACE_SRC="/build/dspace-src"
DSPACE_INSTALL="/dspace"
DSPACE_CFG_DIR="$(dirname "$0")/../config"
SERVER_HOSTNAME="${DSPACE_HOSTNAME:-192.168.26.3}"
DB_PASS="${DSPACE_DB_PASSWORD:-DSpace@Hrep2024!}"

# Ensure build directory exists
mkdir -p /build

log "=== DSpace $DSPACE_VERSION Installation ==="
log "Install path: $DSPACE_INSTALL"
log "Server hostname: $SERVER_HOSTNAME"

# Set JAVA_HOME
export JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java))))
export PATH="$JAVA_HOME/bin:$PATH"

java -version 2>&1 | grep -q "17\|21" || { warn "Java 17+ required"; exit 1; }

# ---- Download DSpace source ----
log "Downloading DSpace $DSPACE_VERSION source..."
if [ ! -d "$DSPACE_SRC" ]; then
    cd /build
    wget -q "https://github.com/DSpace/DSpace/releases/download/dspace-${DSPACE_VERSION}/dspace-${DSPACE_VERSION}-src-release.tar.gz" \
        -O dspace-src.tar.gz
    mkdir -p "$DSPACE_SRC"
    tar xzf dspace-src.tar.gz -C "$DSPACE_SRC" --strip-components=1
    ok "Source downloaded and extracted"
else
    warn "Source directory already exists, skipping download"
fi

# ---- Apply local configuration ----
log "Applying local configuration..."
LOCAL_CFG="$DSPACE_SRC/dspace/config/local.cfg"
cp "$DSPACE_SRC/dspace/config/local.cfg.EXAMPLE" "$LOCAL_CFG" 2>/dev/null || touch "$LOCAL_CFG"

cat > "$LOCAL_CFG" <<LOCALCFG
# Harare Polytechnic DSpace 7.6 Configuration
# Generated by install script on $(date)

dspace.dir = ${DSPACE_INSTALL}
dspace.server.url = http://${SERVER_HOSTNAME}:8080/server
dspace.ui.url = http://${SERVER_HOSTNAME}:4000
dspace.name = Harare Polytechnic Institutional Repository
dspace.hostname = ${SERVER_HOSTNAME}

# Database
db.driver = org.postgresql.Driver
db.url = jdbc:postgresql://localhost:5432/dspace
db.username = dspace
db.password = ${DB_PASS}
db.schema = public

# Solr
solr.server = http://localhost:8983/solr

# Email (configure with your SMTP)
mail.server = localhost
mail.from.address = dspace@hrepoly.ac.zw
mail.feedback.recipient = dspace-help@hrepoly.ac.zw
mail.admin = dspace-admin@hrepoly.ac.zw
mail.server.username =
mail.server.password =
mail.server.port = 25

# Handle server (update with your Handle.net prefix if registered)
handle.canonical.prefix = http://${SERVER_HOSTNAME}:8080/handle/
handle.prefix = 123456789

# Default language
default.locale = en

# Webserver settings
useProxies = false
LOCALCFG

ok "local.cfg configured"

# ---- Build DSpace ----
log "Building DSpace (this takes 5-15 minutes)..."
cd "$DSPACE_SRC"
mvn -q --batch-mode package -Denv=local -P \!dspace-angular 2>&1 | tee /tmp/dspace-build.log
ok "Build complete"

# ---- Install DSpace ----
log "Installing DSpace to $DSPACE_INSTALL..."
mkdir -p "$DSPACE_INSTALL"
chown dspace:dspace "$DSPACE_INSTALL"

cd "$DSPACE_SRC/dspace/target/dspace-installer"
sudo -u dspace ant fresh_install 2>&1 | tee /tmp/dspace-install.log
ok "DSpace backend installed"

# ---- Deploy to Tomcat ----
log "Deploying DSpace REST API to Tomcat..."
TOMCAT_WEBAPPS="/opt/tomcat/webapps"

# Copy the server webapp
cp -r "$DSPACE_INSTALL/webapps/server" "$TOMCAT_WEBAPPS/"
chown -R dspace:dspace "$TOMCAT_WEBAPPS/server"
ok "REST API deployed to Tomcat"

# ---- Configure Solr cores ----
log "Configuring Solr cores for DSpace..."
# Wait for Solr to be ready
for i in {1..12}; do
    curl -sf http://localhost:8983/solr/ &>/dev/null && break
    [ $i -eq 12 ] && { warn "Solr not responding after 60s"; break; }
    sleep 5
done

for CORE in search authority statistics oai; do
    CORE_SRC="$DSPACE_INSTALL/solr/${CORE}"
    if [ -d "$CORE_SRC" ]; then
        sudo -u solr cp -r "$CORE_SRC" /var/solr/data/ 2>/dev/null || \
            cp -r "$CORE_SRC" /var/solr/data/
        ok "Solr core '$CORE' configured"
    fi
done

# Restart Solr to pick up cores
systemctl restart solr

# ---- Start Tomcat ----
log "Starting Tomcat..."
systemctl daemon-reload
systemctl enable tomcat
systemctl start tomcat

ok "=== DSpace $DSPACE_VERSION backend installation complete! ==="
echo ""
echo "Backend REST API: http://${SERVER_HOSTNAME}:8080/server"
echo "Solr admin:       http://${SERVER_HOSTNAME}:8983/solr"
echo ""
echo "Next step: Run  scripts/05-install-angular-ui.sh  for the frontend"
echo "           Then: scripts/06-create-admin.sh  to create admin account"
