#!/usr/bin/env bash
# =============================================================================
#  ChengetAi DSpace Engine — ssl-setup.sh
#  Configures HTTPS for DSpace via self-signed or Let's Encrypt.
#  Usage:  bash engines/dspace-engine/scripts/ssl-setup.sh [--selfsigned|--letsencrypt]
# =============================================================================

set -euo pipefail

ENGINE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
COMMON_DIR="$(cd "$ENGINE_DIR/../common" && pwd)"

source "$COMMON_DIR/logging.sh"
source "$COMMON_DIR/ssl.sh"

ENV_FILE="$ENGINE_DIR/.env"
[ -f "$ENV_FILE" ] && { set -a; source "$ENV_FILE"; set +a; }

HOSTNAME="${DSPACE_HOSTNAME:-localhost}"
CERT_DIR="/etc/ssl/chengetai"
MODE="${1:-}"

log_banner "ChengetAi DSpace — SSL Setup"

# ---- Select mode ----------------------------------------------------------- #
if [ -z "$MODE" ]; then
  echo "SSL options:"
  echo "  1) Self-signed certificate  (instant, no domain required)"
  echo "  2) Let's Encrypt            (trusted, requires a public domain)"
  echo ""
  read -rp "Choose [1/2]: " CHOICE
  case "$CHOICE" in
    1) MODE="--selfsigned" ;;
    2) MODE="--letsencrypt" ;;
    *) log_die "Invalid choice" ;;
  esac
fi

case "$MODE" in
  --selfsigned)
    ssl_self_signed "$HOSTNAME" "$CERT_DIR"
    CERT_CRT="$CERT_DIR/server.crt"
    CERT_KEY="$CERT_DIR/server.key"
    ;;
  --letsencrypt)
    EMAIL="${ADMIN_EMAIL:-admin@$HOSTNAME}"
    LE_DIR=$(ssl_letsencrypt "$HOSTNAME" "$EMAIL" dspace-nginx)
    CERT_CRT="$LE_DIR/fullchain.pem"
    CERT_KEY="$LE_DIR/privkey.pem"
    ;;
  *)
    log_die "Unknown mode: $MODE (use --selfsigned or --letsencrypt)"
    ;;
esac

# ---- Write HTTPS Nginx config ---------------------------------------------- #
log_step "Writing HTTPS Nginx configuration"
cat > "$ENGINE_DIR/config/nginx.conf" <<NGINXCONF
# ChengetAi DSpace Engine — Nginx HTTPS Configuration
# Generated by ssl-setup.sh on $(date)

upstream dspace_backend  { server dspace-backend:8080;  keepalive 32; }
upstream dspace_frontend { server dspace-frontend:4000; keepalive 32; }

# HTTP → HTTPS redirect
server {
    listen 80;
    server_name $HOSTNAME _;
    return 301 https://\$host\$request_uri;
}

server {
    listen 443 ssl;
    http2 on;
    server_name $HOSTNAME _;

    ssl_certificate     $CERT_CRT;
    ssl_certificate_key $CERT_KEY;

    ssl_protocols        TLSv1.2 TLSv1.3;
    ssl_ciphers          ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384;
    ssl_prefer_server_ciphers off;
    ssl_session_cache    shared:SSL:10m;
    ssl_session_timeout  1d;

    client_max_body_size 512M;
    client_body_timeout  300s;

    location /server {
        proxy_pass         http://dspace_backend;
        proxy_set_header   Host               \$host;
        proxy_set_header   X-Real-IP          \$remote_addr;
        proxy_set_header   X-Forwarded-For    \$proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto  https;
        proxy_read_timeout 300s;
        proxy_http_version 1.1;
        proxy_set_header   Connection "";
    }

    location / {
        proxy_pass         http://dspace_frontend;
        proxy_set_header   Host               \$host;
        proxy_set_header   X-Real-IP          \$remote_addr;
        proxy_set_header   X-Forwarded-For    \$proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto  https;
        proxy_read_timeout 300s;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade            \$http_upgrade;
        proxy_set_header   Connection         "upgrade";
    }

    add_header X-Frame-Options        "SAMEORIGIN"                   always;
    add_header X-Content-Type-Options "nosniff"                      always;
    add_header Referrer-Policy        "strict-origin-when-cross-origin" always;
    add_header X-XSS-Protection       "1; mode=block"                always;
    # Uncomment after confirming HTTPS works:
    # add_header Strict-Transport-Security "max-age=63072000" always;

    access_log /var/log/nginx/dspace_access.log;
    error_log  /var/log/nginx/dspace_error.log;
}
NGINXCONF

log_ok "nginx.conf updated for HTTPS"

# ---- Update .env with https ------------------------------------------------ #
sed -i "s|^PUBLIC_PROTOCOL=.*|PUBLIC_PROTOCOL=https|" "$ENV_FILE"
sed -i "s|^DSPACE_UI_SSL=.*|DSPACE_UI_SSL=true|"     "$ENV_FILE" 2>/dev/null || true
sed -i "s|^DSPACE_REST_SSL=.*|DSPACE_REST_SSL=true|" "$ENV_FILE" 2>/dev/null || true
sed -i "s|^DSPACE_REST_PORT=.*|DSPACE_REST_PORT=443|" "$ENV_FILE" 2>/dev/null || true
log_ok ".env updated (PUBLIC_PROTOCOL=https)"

# ---- Re-render local.cfg with https URLs ----------------------------------- #
log_step "Re-rendering local.cfg"
source "$ENV_FILE"
RENDERED_CFG="$ENGINE_DIR/config/local.cfg"
sed \
  -e "s|%%DSPACE_HOSTNAME%%|${DSPACE_HOSTNAME}|g" \
  -e "s|%%POSTGRES_PASSWORD%%|${POSTGRES_PASSWORD}|g" \
  -e "s|%%SMTP_HOST%%|${SMTP_HOST:-localhost}|g" \
  -e "s|%%SMTP_PORT%%|${SMTP_PORT:-25}|g" \
  -e "s|%%DSPACE_NAME%%|${DSPACE_NAME:-DSpace Repository}|g" \
  -e "s|%%HANDLE_PREFIX%%|${HANDLE_PREFIX:-123456789}|g" \
  -e "s|%%MAIL_FROM%%|${MAIL_FROM:-dspace@localhost}|g" \
  -e "s|%%PUBLIC_PROTOCOL%%|https|g" \
  "$ENGINE_DIR/templates/local.cfg.tpl" > "$RENDERED_CFG"
log_ok "local.cfg updated with https:// URLs"

# ---- Reload Nginx ---------------------------------------------------------- #
log_step "Reloading Nginx"
docker exec dspace-nginx nginx -s reload 2>/dev/null || \
  docker compose -f "$ENGINE_DIR/docker-compose.yml" --env-file "$ENV_FILE" \
    restart nginx

# ---- Restart DSpace backend with new URLs ---------------------------------- #
log_step "Restarting DSpace backend to apply new URLs"
docker compose -f "$ENGINE_DIR/docker-compose.yml" --env-file "$ENV_FILE" \
  up -d --no-deps dspace

log_ok "HTTPS enabled"
echo ""
echo "  Repository: https://${HOSTNAME}/"
echo "  API:        https://${HOSTNAME}/server/"
